  esphome:
    name: esphome-web-sa1200p
    friendly_name: ESPHome SA1200P CO2
    platform: ESP8266
    board: d1_mini
    includes:
      - cubic_cm1106c_passive_sensor.h
  
  # Enable Home Assistant API
  api:

  # Enable logging
  logger:
    baud_rate: 0
  
  ota:
    password: !secret ota_password
    
  wifi:
    networks:
    - ssid: !secret wifi_ssid
      password: !secret wifi_password
    reboot_timeout: 15min
  
    # Enable fallback hotspot (captive portal) in case wifi connection fails
    ap:
      ssid: "Fallback Hotspot SA1200P"
      password: !secret fallback_ssid_password
  
  captive_portal:
  
  uart:
    - rx_pin: GPIO05 # D1 pin on D1 Mini
      tx_pin: GPIO04 # D2 pin on D1 Mini
      baud_rate: 9600
      id: uart_0
  
  sensor:
    - platform: custom
      lambda: |-
        auto cm1106c_passive_sensor = new CM1106CPassiveSensor(id(uart_0));
        App.register_component(cm1106c_passive_sensor);
        return {cm1106c_passive_sensor};
      sensors:
        name: "yoursensorname.airquality.co2"
        unit_of_measurement: "ppm"